version: "3.8"
services:
  resqplate:
    image: resqplate-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: resqplate-dev-c
    volumes:
      - ./resqplate:/resqplate
      - node_modules:/resqplate/node_modules/
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
volumes:
  node_modules: